//! Sprint-14 S14-2 — make the shared `JSONPath` fixture load-bearing.
//!
//! `tests/jsonpath_fixtures.json` is generated by the
//! `jsonpath-fixture-gen` binary and is meant to be the canonical
//! contract shared between the backend redaction engine and the S14-6
//! frontend parity test. Until this test existed the `expected_masked`
//! literals were hand-written and **never run through the real engine**
//! — so the recursive-descent (`$..token`) and wildcard (`$.*`, `$.*`
//! over arrays) cases, exactly where `jsonpath_lib` 0.3 has behavioural
//! quirks, were unverified.
//!
//! This test loads every fixture case and threads its input through
//! `RedactionRules::apply` once per `JSONPath` selector (mirroring how a
//! multi-rule tenant policy composes), then asserts the result matches
//! the fixture's `expected_masked`. A drift between the generated
//! literals and the live engine now fails CI instead of silently
//! shipping a wrong contract to the frontend.

use serde_json::Value;
use xiaoguai_auth::redaction::RedactionRules;
use xiaoguai_storage::repositories::hotl_redaction::RedactionPolicyRow;

/// Scope used for every synthetic single-rule policy in this test. The
/// fixtures are scope-agnostic (they pin `JSONPath` semantics, not scope
/// selection), so any non-wildcard scope reused consistently works.
const FIXTURE_SCOPE: &str = "fixture_scope";

/// Build a single active SSE-path rule carrying one `JSONPath` selector.
fn single_rule(jsonpath: &str) -> RedactionPolicyRow {
    RedactionPolicyRow {
        id: uuid::Uuid::new_v4(),
        tenant_id: uuid::Uuid::new_v4(),
        scope: FIXTURE_SCOPE.to_string(),
        jsonpath: jsonpath.to_string(),
        applies_to: vec!["sse".to_string()],
        created_at: chrono::Utc::now(),
        active: true,
        created_by: "fixture-parity-test".to_string(),
        supersedes_policy_id: None,
    }
}

/// Apply every selector in `jsonpaths` to `input`, threading the masked
/// output of each into the next — the same cumulative effect a tenant
/// with one rule per selector would see.
fn apply_all(jsonpaths: &[String], input: &Value) -> Value {
    jsonpaths.iter().fold(input.clone(), |acc, jsonpath| {
        let rules = RedactionRules::new(vec![single_rule(jsonpath)]);
        rules.apply(FIXTURE_SCOPE, &acc)
    })
}

#[test]
fn fixture_expected_masked_matches_live_engine() {
    let raw = include_str!("jsonpath_fixtures.json");
    let doc: Value = serde_json::from_str(raw).expect("fixture json parses");

    let cases = doc
        .get("cases")
        .and_then(Value::as_array)
        .expect("fixture has a `cases` array");
    assert!(!cases.is_empty(), "fixture must define at least one case");

    let mut checked = 0;
    for case in cases {
        let name = case
            .get("name")
            .and_then(Value::as_str)
            .expect("case has a name");
        let jsonpaths: Vec<String> = case
            .get("jsonpaths")
            .and_then(Value::as_array)
            .unwrap_or_else(|| panic!("case `{name}` has a jsonpaths array"))
            .iter()
            .map(|v| {
                v.as_str()
                    .unwrap_or_else(|| panic!("case `{name}` jsonpath entry must be a string"))
                    .to_string()
            })
            .collect();
        let input = case
            .get("input")
            .unwrap_or_else(|| panic!("case `{name}` has an input"));
        let expected = case
            .get("expected_masked")
            .unwrap_or_else(|| panic!("case `{name}` has an expected_masked"));

        let actual = apply_all(&jsonpaths, input);
        assert_eq!(
            &actual, expected,
            "case `{name}`: live engine output diverged from the generated \
             fixture literal (jsonpaths={jsonpaths:?}); regenerate via \
             `cargo run --bin jsonpath-fixture-gen` or fix the engine"
        );
        checked += 1;
    }

    assert_eq!(checked, cases.len(), "every fixture case must be exercised");
}
