//! `Plan` + `Task` types. The Planner emits one of these per planning
//! round; the orchestrator dispatches each `Task` to a Worker.
//!
//! `TaskId` is `Copy` and quarantine-key for the per-task `Scratchpad`
//! — Workers can never read each other's notes.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Stable identifier for a single task within one plan. Quarantine
/// key for the per-task `Scratchpad`. UUIDv4 — picked here for
/// `Copy`-ability and lack of cross-process serialisation drift.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TaskId(pub Uuid);

impl TaskId {
    /// Fresh random id. Generated by the orchestrator when it parses
    /// a `Plan` — the Planner does NOT supply ids.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for TaskId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for TaskId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// What the Critic checks for to decide Approve / RequestRevision /
/// Reject. The Planner emits this alongside each task description so
/// the Critic has a stable rubric to grade against (without it the
/// Critic would have to infer criteria, leading to noisy verdicts).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AcceptanceCriteria {
    /// Plain-text rubric the Critic injects into its prompt.
    pub rubric: String,
    /// If `Some`, the Critic must verify the result includes at least
    /// one citation matching this pattern (substring match for now).
    pub required_citation_pattern: Option<String>,
    /// Minimum confidence the Worker must report for Approve to be
    /// possible. 0.0..=1.0; `None` means "no floor".
    pub min_confidence: Option<f32>,
}

/// One step in a `Plan`. Workers consume these one at a time; the
/// orchestrator decides Task→Worker assignment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Task {
    pub id: TaskId,
    pub description: String,
    pub acceptance_criteria: AcceptanceCriteria,
    /// `None` = no dependency, runnable immediately. `Some(other)` =
    /// must wait for `other` to be Approved before this Task may
    /// dispatch. Cycles are rejected at `Plan::validate` time.
    pub depends_on: Option<TaskId>,
}

/// One planning round's output. Replans produce a fresh `Plan` with a
/// new `round` value; old Plan contents are kept for the final
/// summary aggregator.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Plan {
    pub round: u32,
    pub goal: String,
    pub tasks: Vec<Task>,
    pub created_at: DateTime<Utc>,
}

impl Plan {
    /// Reject malformed plans before any Worker is spawned. Checks:
    /// non-empty `goal`, non-empty `tasks`, no duplicate task ids
    /// (the orchestrator assigns ids; if a Planner-supplied JSON
    /// included clashing ids the parse would already have failed —
    /// this guards programmatic construction in tests too).
    ///
    /// # Errors
    /// Returns the first reason the plan is invalid; callers retry
    /// the Planner with the reason injected as context.
    pub fn validate(&self) -> Result<(), PlanValidationError> {
        if self.goal.trim().is_empty() {
            return Err(PlanValidationError::EmptyGoal);
        }
        if self.tasks.is_empty() {
            return Err(PlanValidationError::EmptyTasks);
        }
        let mut ids = std::collections::HashSet::new();
        for t in &self.tasks {
            if !ids.insert(t.id) {
                return Err(PlanValidationError::DuplicateTaskId(t.id));
            }
        }
        // depends_on cycles — limited to depth 1 today (tasks form a
        // DAG of height ≤ 2); future Planners that emit deeper chains
        // will need a topological check.
        for t in &self.tasks {
            if let Some(dep) = t.depends_on {
                if dep == t.id {
                    return Err(PlanValidationError::SelfDependency(t.id));
                }
                if !ids.contains(&dep) {
                    return Err(PlanValidationError::UnknownDependency {
                        task: t.id,
                        depends_on: dep,
                    });
                }
            }
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum PlanValidationError {
    #[error("plan goal is empty")]
    EmptyGoal,
    #[error("plan has no tasks")]
    EmptyTasks,
    #[error("duplicate task id: {0}")]
    DuplicateTaskId(TaskId),
    #[error("task {0} depends on itself")]
    SelfDependency(TaskId),
    #[error("task {task} depends on unknown task {depends_on}")]
    UnknownDependency { task: TaskId, depends_on: TaskId },
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ac() -> AcceptanceCriteria {
        AcceptanceCriteria {
            rubric: "non-empty answer".into(),
            required_citation_pattern: None,
            min_confidence: None,
        }
    }

    fn fresh_task(desc: &str) -> Task {
        Task {
            id: TaskId::new(),
            description: desc.into(),
            acceptance_criteria: ac(),
            depends_on: None,
        }
    }

    #[test]
    fn task_ids_are_unique() {
        let a = TaskId::new();
        let b = TaskId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn plan_validate_empty_goal_rejected() {
        let p = Plan {
            round: 0,
            goal: "   ".into(),
            tasks: vec![fresh_task("x")],
            created_at: Utc::now(),
        };
        assert_eq!(p.validate(), Err(PlanValidationError::EmptyGoal));
    }

    #[test]
    fn plan_validate_empty_tasks_rejected() {
        let p = Plan {
            round: 0,
            goal: "g".into(),
            tasks: vec![],
            created_at: Utc::now(),
        };
        assert_eq!(p.validate(), Err(PlanValidationError::EmptyTasks));
    }

    #[test]
    fn plan_validate_duplicate_ids_rejected() {
        let t = fresh_task("a");
        let dup = Task { ..t.clone() };
        let p = Plan {
            round: 0,
            goal: "g".into(),
            tasks: vec![t.clone(), dup],
            created_at: Utc::now(),
        };
        assert_eq!(p.validate(), Err(PlanValidationError::DuplicateTaskId(t.id)));
    }

    #[test]
    fn plan_validate_self_dependency_rejected() {
        let id = TaskId::new();
        let p = Plan {
            round: 0,
            goal: "g".into(),
            tasks: vec![Task {
                id,
                description: "self".into(),
                acceptance_criteria: ac(),
                depends_on: Some(id),
            }],
            created_at: Utc::now(),
        };
        assert_eq!(p.validate(), Err(PlanValidationError::SelfDependency(id)));
    }

    #[test]
    fn plan_validate_unknown_dependency_rejected() {
        let phantom = TaskId::new();
        let real = fresh_task("a");
        let p = Plan {
            round: 0,
            goal: "g".into(),
            tasks: vec![Task {
                id: real.id,
                description: "real".into(),
                acceptance_criteria: ac(),
                depends_on: Some(phantom),
            }],
            created_at: Utc::now(),
        };
        assert_eq!(
            p.validate(),
            Err(PlanValidationError::UnknownDependency {
                task: real.id,
                depends_on: phantom,
            })
        );
    }

    #[test]
    fn plan_validate_happy_path() {
        let a = fresh_task("a");
        let b = Task {
            id: TaskId::new(),
            description: "b".into(),
            acceptance_criteria: ac(),
            depends_on: Some(a.id),
        };
        let p = Plan {
            round: 0,
            goal: "g".into(),
            tasks: vec![a, b],
            created_at: Utc::now(),
        };
        assert_eq!(p.validate(), Ok(()));
    }

    #[test]
    fn plan_round_trips_through_serde() {
        let p = Plan {
            round: 3,
            goal: "g".into(),
            tasks: vec![fresh_task("a")],
            created_at: Utc::now(),
        };
        let json = serde_json::to_string(&p).unwrap();
        let back: Plan = serde_json::from_str(&json).unwrap();
        assert_eq!(p, back);
    }
}
