-- Migration: 0001_kanban_meta
-- Pack: kanban-automation
-- Created: 2026-05-25
--
-- Pack-specific metadata tables for the kanban-automation pack.
-- These are NOT the core tasks/columns tables (that is the kanban subsystem,
-- task #150, shipping in v1.4).  This migration only creates the agent
-- side-channel data that the five kanban agents read and write.
--
-- Idempotent: all statements use IF NOT EXISTS.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. triage_classifications
--    One row per card that has been processed by the incoming-triager agent.
--    References the logical card id (UUID) that will exist in the kanban
--    subsystem once task #150 ships; until then the column is nullable and
--    rows accumulate in dry-run mode.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS kanban_triage_classifications (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Card reference (nullable until kanban subsystem ships).
    card_id             UUID,               -- FK into kanban tasks table (v1.4)
    inbound_source      TEXT        NOT NULL, -- 'slack' | 'email' | 'pagerduty' | 'manual' | 'pack'
    inbound_ref         TEXT,               -- e.g. Slack ts, email message-id, PD incident id

    -- Classification outputs from incoming-triager.
    card_type           TEXT        NOT NULL, -- 'bug' | 'feature' | 'task' | 'incident' | 'question'
    urgency             TEXT        NOT NULL, -- 'critical' | 'high' | 'medium' | 'low'
    owner_hint          TEXT,               -- suggested owner team/person (may be NULL)
    triage_confidence   TEXT        NOT NULL, -- 'high' | 'medium' | 'low'
    triage_rationale    TEXT,               -- LLM reasoning (max 1000 chars stored)

    -- Timestamps
    classified_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    card_created_at     TIMESTAMPTZ,        -- set when kanban subsystem confirms card creation

    -- Raw card content snapshot (for debugging; trimmed to 4000 chars)
    content_snapshot    TEXT,

    CONSTRAINT urgency_values   CHECK (urgency   IN ('critical', 'high', 'medium', 'low')),
    CONSTRAINT card_type_values CHECK (card_type IN ('bug', 'feature', 'task', 'incident', 'question')),
    CONSTRAINT confidence_values CHECK (triage_confidence IN ('high', 'medium', 'low'))
);

CREATE INDEX IF NOT EXISTS idx_ktc_card_id
    ON kanban_triage_classifications (card_id)
    WHERE card_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ktc_inbound_source
    ON kanban_triage_classifications (inbound_source, classified_at DESC);

CREATE INDEX IF NOT EXISTS idx_ktc_urgency
    ON kanban_triage_classifications (urgency, classified_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. split_suggestions
--    Proposals generated by the oversized-detector agent.
--    Each row represents one suggested sub-card within a split.
--    A human or HotL approver must act on the proposal before
--    card-split-execute posts to /v1/tasks/{id}/split.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS kanban_split_suggestions (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Parent card being split.
    parent_card_id      UUID,               -- FK into kanban tasks (v1.4, nullable until then)
    classification_id   UUID        REFERENCES kanban_triage_classifications(id) ON DELETE SET NULL,

    -- Estimated effort of the *original* card (what triggered the split).
    original_est_effort TEXT        NOT NULL, -- e.g. '2d', '1.5d', '8h'
    -- Effort-estimation basis used by oversized-detector.
    effort_basis        TEXT        NOT NULL, -- see comment below on estimation method

    -- Individual sub-card proposal.
    -- Multiple rows share the same (parent_card_id, proposal_batch) for a
    -- single split event.
    proposal_batch      UUID        NOT NULL DEFAULT gen_random_uuid(),
    sub_card_order      INTEGER     NOT NULL DEFAULT 1,
    sub_card_title      TEXT        NOT NULL,
    sub_card_description TEXT,
    sub_card_est_effort TEXT        NOT NULL, -- e.g. '4h', '1d'
    sub_card_labels     TEXT[],              -- inherited + derived labels

    -- Approval state (HotL gate).
    approval_status     TEXT        NOT NULL DEFAULT 'pending',
    approved_by         TEXT,               -- user/agent that approved
    approved_at         TIMESTAMPTZ,
    rejection_reason    TEXT,

    -- Execution state (requires XIAOGUAI_KANBAN_ENABLED + task #150).
    executed_at         TIMESTAMPTZ,        -- set when split POST succeeded
    resulting_card_id   UUID,               -- card id returned by /v1/tasks/{id}/split

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT approval_status_values
        CHECK (approval_status IN ('pending', 'approved', 'rejected', 'executed', 'skipped'))
);

-- Effort estimation method note (stored in effort_basis column):
-- The oversized-detector uses a two-signal heuristic:
--   1. KEYWORD SCAN: card title + description are scanned for scope signals
--      (e.g. "migrate all", "refactor entire", "implement end-to-end") that
--      historically correlate with >1d effort.  Each match adds weight.
--   2. LABEL HINTS: if the auto-tagger assigned complexity=high or the card
--      type is 'feature', baseline estimate starts at 1d.
--   3. LLM ESTIMATE: the agent sends the card content to the LLM with a
--      prompt asking for an effort estimate in the format "<N><unit>" where
--      unit is h (hours) or d (days).  The LLM output is parsed and validated;
--      if parsing fails the agent falls back to keyword-scan result.
-- basis field stores: 'keyword-scan' | 'llm-estimate' | 'label-hint' | 'combined'
-- A card is flagged oversized when the resolved estimate > 8h (1 working day).

CREATE INDEX IF NOT EXISTS idx_kss_parent_card
    ON kanban_split_suggestions (parent_card_id)
    WHERE parent_card_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_kss_proposal_batch
    ON kanban_split_suggestions (proposal_batch, sub_card_order);

CREATE INDEX IF NOT EXISTS idx_kss_approval_status
    ON kanban_split_suggestions (approval_status, created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. agent_workload_snapshots
--    Point-in-time snapshots of agent workload taken by workload-balancer.
--    Used to trend idle time and validate balancing decisions over time.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS kanban_agent_workload_snapshots (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The worker being snapshotted.
    worker_id           TEXT        NOT NULL, -- agent/human id from the worker pool
    worker_type         TEXT        NOT NULL, -- 'llm-agent' | 'human'
    worker_specialties  TEXT[],              -- tags this worker handles well

    -- Board state at snapshot time.
    in_progress_count   INTEGER     NOT NULL DEFAULT 0,
    ready_queue_depth   INTEGER     NOT NULL DEFAULT 0,
    blocked_count       INTEGER     NOT NULL DEFAULT 0,

    -- Idle detection.
    is_idle             BOOLEAN     NOT NULL DEFAULT FALSE,
    idle_since          TIMESTAMPTZ,

    -- Card suggested by workload-balancer when idle (v1.4-ready).
    suggested_card_id   UUID,
    suggestion_rationale TEXT,
    suggestion_acted_on BOOLEAN     NOT NULL DEFAULT FALSE,

    snapshot_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT worker_type_values CHECK (worker_type IN ('llm-agent', 'human'))
);

CREATE INDEX IF NOT EXISTS idx_kaws_worker
    ON kanban_agent_workload_snapshots (worker_id, snapshot_at DESC);

CREATE INDEX IF NOT EXISTS idx_kaws_idle
    ON kanban_agent_workload_snapshots (is_idle, snapshot_at DESC)
    WHERE is_idle = TRUE;
