-- Migration: 0001_mentions
-- Media monitoring core schema.
--
-- Tables:
--   mentions         — raw normalized mention records from all channels
--   sentiment_history — per-mention sentiment classification results (append-only)
--   crisis_events    — crisis early warning records with resolution tracking

-- ---------------------------------------------------------------------------
-- mentions
-- ---------------------------------------------------------------------------
-- Each row represents one brand mention captured from any inbound channel.
-- Immutable after insert; enrichment lives in sentiment_history.
CREATE TABLE IF NOT EXISTS mentions (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Source channel: twitter | reddit | hackernews | news | instagram
    channel         TEXT        NOT NULL CHECK (channel IN ('twitter', 'reddit', 'hackernews', 'news', 'instagram')),
    -- Stable external ID from the source platform (e.g. tweet id, post id).
    external_id     TEXT        NOT NULL,
    -- Unique per channel — prevents duplicate ingestion.
    UNIQUE (channel, external_id),
    -- Author / account identifier (username or display name).
    author          TEXT,
    -- Raw mention text (truncated to 4096 chars at ingest).
    body            TEXT        NOT NULL CHECK (char_length(body) <= 4096),
    -- URL to the original mention.
    url             TEXT,
    -- Estimated reach: follower count, subreddit subscribers, etc.
    reach           BIGINT      NOT NULL DEFAULT 0,
    -- Upvotes, likes, retweets etc. at time of capture.
    engagement      BIGINT      NOT NULL DEFAULT 0,
    -- Keywords that triggered this capture (array of brand/product terms).
    matched_keywords TEXT[]     NOT NULL DEFAULT '{}',
    -- UTC timestamp from the source platform.
    published_at    TIMESTAMPTZ NOT NULL,
    -- UTC timestamp when xiaoguai ingested the record.
    ingested_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mentions_channel_published ON mentions (channel, published_at DESC);
CREATE INDEX IF NOT EXISTS mentions_published_at ON mentions (published_at DESC);
CREATE INDEX IF NOT EXISTS mentions_matched_keywords ON mentions USING GIN (matched_keywords);

-- ---------------------------------------------------------------------------
-- sentiment_history
-- ---------------------------------------------------------------------------
-- Append-only log of LLM sentiment classifications for each mention.
-- Multiple rows per mention are valid (e.g. reclassification on model update).
-- The latest row (classified_at DESC) is considered canonical.
CREATE TABLE IF NOT EXISTS sentiment_history (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    mention_id      UUID        NOT NULL REFERENCES mentions (id) ON DELETE CASCADE,
    -- Sentiment label: positive | neutral | negative
    sentiment       TEXT        NOT NULL CHECK (sentiment IN ('positive', 'neutral', 'negative')),
    -- Model confidence [0.0, 1.0].
    confidence      NUMERIC(4,3) NOT NULL CHECK (confidence BETWEEN 0.0 AND 1.0),
    -- Key phrase(s) extracted by the classifier (up to 5).
    key_phrases     TEXT[]      NOT NULL DEFAULT '{}',
    -- LLM model identifier used for this classification.
    model_id        TEXT        NOT NULL,
    -- Outcome feedback recorded by outcome-telemetry (correct | incorrect | unknown).
    outcome         TEXT        CHECK (outcome IN ('correct', 'incorrect', 'unknown')),
    classified_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sentiment_history_mention ON sentiment_history (mention_id, classified_at DESC);
CREATE INDEX IF NOT EXISTS sentiment_history_classified_at ON sentiment_history (classified_at DESC);
CREATE INDEX IF NOT EXISTS sentiment_history_sentiment ON sentiment_history (sentiment, classified_at DESC);

-- ---------------------------------------------------------------------------
-- crisis_events
-- ---------------------------------------------------------------------------
-- A crisis event is declared when crisis-early-warner fires.
-- Resolved when PR team marks it closed or automatically after 48h with no
-- new triggering anomalies.
CREATE TABLE IF NOT EXISTS crisis_events (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Short human-readable title generated by crisis-early-warner.
    title           TEXT        NOT NULL,
    -- Trigger reason: volume_spike | sentiment_crash | combined
    trigger_type    TEXT        NOT NULL CHECK (trigger_type IN ('volume_spike', 'sentiment_crash', 'combined')),
    -- Severity assessed at declaration time: sev1 | sev2 | sev3
    severity        TEXT        NOT NULL CHECK (severity IN ('sev1', 'sev2', 'sev3')),
    -- Dominant channel(s) where crisis originated.
    channels        TEXT[]      NOT NULL DEFAULT '{}',
    -- Snapshot metrics at time of declaration.
    hourly_mention_count  INTEGER NOT NULL DEFAULT 0,
    z_score               NUMERIC(6,2),
    negative_ratio        NUMERIC(4,3) CHECK (negative_ratio BETWEEN 0.0 AND 1.0),
    influence_weighted_reach BIGINT NOT NULL DEFAULT 0,
    -- Narrative summary produced by crisis-early-warner agent.
    narrative       TEXT,
    -- Resolution state: open | monitoring | resolved | false_positive
    status          TEXT        NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open', 'monitoring', 'resolved', 'false_positive')),
    -- Optional PagerDuty incident ID for cross-reference.
    pagerduty_incident_id TEXT,
    declared_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at     TIMESTAMPTZ,
    -- FK to the most recent response-draft recommendation, if generated.
    response_recommendation_id UUID
);

CREATE INDEX IF NOT EXISTS crisis_events_status ON crisis_events (status, declared_at DESC);
CREATE INDEX IF NOT EXISTS crisis_events_declared_at ON crisis_events (declared_at DESC);
