-- 0014 (SQLite single-user, DEC-033): NO-OP.
--
-- The Postgres version added `tenants.rate_limit_class`. The tenants table is
-- dropped under the single-user pivot and per-tenant rate-limiting is
-- meaningless for a single local owner, so there is nothing to apply here. The
-- file is retained (not deleted) to preserve the 1:1 migration numbering and
-- sqlx's applied-version history.
